from constants.map.positions import START_AVARI, START_KELGRAS, START_LEVIATHAN, START_THERON
from constants.names import OG_AVARI, OG_KELGRAS, OG_LEVIATHAN, OG_THERON, R_MINERAL, R_WATER, R_WHEAT, R_WOOD

DOMINANT_RESOURCES = {
    OG_AVARI: R_WHEAT,
    OG_KELGRAS: R_WOOD,
    OG_LEVIATHAN: R_WATER,
    OG_THERON: R_MINERAL
}

START_C = {
    OG_AVARI: START_AVARI,
    OG_KELGRAS: START_KELGRAS,
    OG_LEVIATHAN: START_LEVIATHAN,
    OG_THERON: START_THERON
}

OG_NAME = "ogName"
OG_DOMINANT_RESOURCES = "ogDom"
OG_ACTIVE_ID = "ogActiveId"
OG_RMULTIPLIER = "ogMult"
OG_FORCE = "ogForce"
OG_INSURANCE = "ogInsurance"
OG_NO = "ogNo"
OG_COLLATERAL = "ogCol"
OG_USED_POWERUPS = "ogUsed"
OG_MISC = "ogMisc"
