from constants.names import OG_AVARI, OG_KELGRAS, OG_LEVIATHAN, OG_THERON, R_MINERAL, R_WATER, R_WHEAT, R_WOOD

DOMINANT_RESOURCES = {
    OG_AVARI: R_WHEAT,
    OG_KELGRAS: R_WOOD,
    OG_LEVIATHAN: R_WATER,
    OG_THERON: R_MINERAL
}