import math
import numpy as np

BORDER_SIZE = 200
CENTER_HEX = np.array([1917 + BORDER_SIZE, 1089 + BORDER_SIZE])
HEX_DIAMETER = 455
HEX_SIDE = 265
HEX_RADIUS_EDGE = HEX_DIAMETER/2
HEX_RADIUS_VERTEX = math.sqrt(HEX_RADIUS_EDGE**2 + (HEX_SIDE/2)**2)